/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package updatedatabase;

import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.sql.Statement;

/**
 *
 * @author Uexcel
 */
public class DatabaseUpdate extends javax.swing.JFrame {

    /**
     * Creates new form UpdateDatabase
     */
    public DatabaseUpdate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tableName = new javax.swing.JTextField();
        columnUpdating = new javax.swing.JTextField();
        conditionColumn = new javax.swing.JTextField();
        conditionValue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        newValue = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Database Updatee");
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 350));
        jPanel1.setLayout(null);

        tableName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableNameActionPerformed(evt);
            }
        });
        jPanel1.add(tableName);
        tableName.setBounds(20, 60, 200, 30);
        jPanel1.add(columnUpdating);
        columnUpdating.setBounds(230, 60, 200, 30);

        conditionColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conditionColumnActionPerformed(evt);
            }
        });
        jPanel1.add(conditionColumn);
        conditionColumn.setBounds(230, 140, 200, 30);
        jPanel1.add(conditionValue);
        conditionValue.setBounds(130, 220, 200, 30);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(360, 90, 62, 0);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Column name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 112, 150, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Table name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 32, 140, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Condition");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 190, 90, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("New value");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 112, 90, 30);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 280, 140, 33);
        jPanel1.add(newValue);
        newValue.setBounds(20, 140, 200, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Column name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(250, 32, 150, 30);

        getContentPane().add(jPanel1);

        setSize(new java.awt.Dimension(514, 407));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username = "root";
        String password = "jvman19";
        String url = "jdbc:mariadb://localhost:3306/mydatabase";
        try {
            Connection conn = DriverManager.getConnection(url, username, password);
            Statement statement = conn.createStatement();

            String query = String.format("Update %s SET %s = '%s' WHERE %s = '%s' ",
                    tableName.getText(), columnUpdating.getText(), newValue.getText(), conditionColumn.getText(), conditionValue.getText());
            
            statement.executeQuery(query);
            JOptionPane.showMessageDialog(this, "Successful", "Natification", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            
            JOptionPane.showMessageDialog(this, "We encountered error "+ e, "Natification", JOptionPane.ERROR_MESSAGE);
            tableName.setText("");
            columnUpdating.setText("");
            newValue.setText("");
            conditionColumn.setText("");
            conditionValue.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void conditionColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conditionColumnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conditionColumnActionPerformed

    private void tableNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNameActionPerformed

    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatabaseUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DatabaseUpdate().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField columnUpdating;
    private javax.swing.JTextField conditionColumn;
    private javax.swing.JTextField conditionValue;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField newValue;
    private javax.swing.JTextField tableName;
    // End of variables declaration//GEN-END:variables
}
